version: "3.9"

services:
  rabbitmq-management:
    image: rabbitmq:3-management
    container_name: rabbitmq-management
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - rabbitmq-network
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia

volumes:
  rabbitmq-data:


networks:
  rabbitmq-network:
    driver: bridge
